[build.environment]
HUGO_VERSION = "0.159.0"
NODE_VERSION = "24.14.1"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo build --gc --minify --baseURL "${URL}"
  """